## Basys3 system clock
set_property PACKAGE_PIN W5 [get_ports CLK100MHZ]
set_property IOSTANDARD LVCMOS33 [get_ports CLK100MHZ]
create_clock -name sys_clk -period 10.000 [get_ports CLK100MHZ]
# The 25 MHz VGA/camera XCLK is generated by an MMCM in RTL. Vivado derives
# that generated clock automatically from sys_clk.
# Camera pixel clock is returned by the OV7670 and has board/sensor phase delay,
# so keep it asynchronous to the FPGA-generated clocks.
create_clock -name cam_pclk_clk -period 40.000 [get_ports cam_pclk]
set_clock_groups -asynchronous \
    -group [get_clocks cam_pclk_clk] \
    -group [get_clocks -include_generated_clocks sys_clk]

## Reset button (center)
set_property PACKAGE_PIN U18 [get_ports btnC]
set_property IOSTANDARD LVCMOS33 [get_ports btnC]

## Slide switches
set_property PACKAGE_PIN V17 [get_ports {sw[0]}]
set_property PACKAGE_PIN V16 [get_ports {sw[1]}]
set_property PACKAGE_PIN W16 [get_ports {sw[2]}]
set_property PACKAGE_PIN W17 [get_ports {sw[3]}]
set_property PACKAGE_PIN W15 [get_ports {sw[4]}]
set_property PACKAGE_PIN V15 [get_ports {sw[5]}]
set_property PACKAGE_PIN W14 [get_ports {sw[6]}]
set_property PACKAGE_PIN W13 [get_ports {sw[7]}]
set_property PACKAGE_PIN V2  [get_ports {sw[8]}]
set_property PACKAGE_PIN T3  [get_ports {sw[9]}]
set_property PACKAGE_PIN T2  [get_ports {sw[10]}]
set_property PACKAGE_PIN R3  [get_ports {sw[11]}]
set_property PACKAGE_PIN W2  [get_ports {sw[12]}]
set_property PACKAGE_PIN U1  [get_ports {sw[13]}]
set_property PACKAGE_PIN T1  [get_ports {sw[14]}]
set_property PACKAGE_PIN R2  [get_ports {sw[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports sw[*]]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]
set_property PACKAGE_PIN V3  [get_ports {led[9]}]
set_property PACKAGE_PIN W3  [get_ports {led[10]}]
set_property PACKAGE_PIN U3  [get_ports {led[11]}]
set_property PACKAGE_PIN P3  [get_ports {led[12]}]
set_property PACKAGE_PIN N3  [get_ports {led[13]}]
set_property PACKAGE_PIN P1  [get_ports {led[14]}]
set_property PACKAGE_PIN L1  [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports led[*]]

## OV7670 camera pins (from assignment handout mapping)
set_property PACKAGE_PIN P17 [get_ports {cam_data[0]}] ;# D0
set_property PACKAGE_PIN N17 [get_ports {cam_data[1]}] ;# D1
set_property PACKAGE_PIN M19 [get_ports {cam_data[2]}] ;# D2
set_property PACKAGE_PIN M18 [get_ports {cam_data[3]}] ;# D3
set_property PACKAGE_PIN L17 [get_ports {cam_data[4]}] ;# D4
set_property PACKAGE_PIN K17 [get_ports {cam_data[5]}] ;# D5
set_property PACKAGE_PIN C16 [get_ports {cam_data[6]}] ;# D6
set_property PACKAGE_PIN B16 [get_ports {cam_data[7]}] ;# D7

set_property PACKAGE_PIN A17 [get_ports cam_href]   ;# HREF
set_property PACKAGE_PIN B15 [get_ports cam_vsync]  ;# VSYNC
set_property PACKAGE_PIN A16 [get_ports cam_pclk]   ;# PCLK 
set_property PACKAGE_PIN C15 [get_ports cam_xclk]   ;# XCLK out
set_property PACKAGE_PIN A14 [get_ports cam_sioc]   ;# SCCB SCL
set_property PACKAGE_PIN A15 [get_ports cam_siod]   ;# SCCB SDA
set_property PACKAGE_PIN R18 [get_ports cam_pwdn]   ;# PWDN
set_property PACKAGE_PIN P18 [get_ports cam_reset]  ;# RESET

set_property IOSTANDARD LVCMOS33 [get_ports cam_data[*]]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_href cam_vsync cam_pclk cam_xclk cam_sioc cam_siod cam_pwdn cam_reset}]
set_property PULLUP true [get_ports cam_siod]

## VGA
set_property PACKAGE_PIN G19 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN H19 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN J19 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN N19 [get_ports {vga_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[*]}]

set_property PACKAGE_PIN J17 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN H17 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN G17 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN D17 [get_ports {vga_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[*]}]

set_property PACKAGE_PIN N18 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN L18 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN K18 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN J18 [get_ports {vga_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[*]}]

set_property PACKAGE_PIN P19 [get_ports vga_hsync]
set_property PACKAGE_PIN R19 [get_ports vga_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_hsync vga_vsync}]

## Configuration voltage for Basys3
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
